import { useState } from "react";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogTitle } from "./UI/Dialog";
import { Button } from "./UI/Button";


export default function Disclaimer() {
    const [isDialogOpen, setIsDialogOpen] = useState<boolean>(true)

    return(
        <Dialog open={isDialogOpen} onOpenChange={() => {setIsDialogOpen(!isDialogOpen)}}>
            <DialogContent className="bg-white text-slate-800 font-poppins p-10">
                <DialogTitle>disclaimer!</DialogTitle>
                <DialogDescription>
                    this site is a proof-of-concept and is still quite slow (5-10 seconds depending on input) and can produce incorrect information. make sure to double-check the calendars generated by tab2cal. open on desktop for the best experience.
                </DialogDescription>
                <DialogFooter className="sm:justify-start">
                    <DialogClose asChild>
                        <Button type="button" className="bg-blue-500 text-white">
                            gotcha
                        </Button>
                    </DialogClose>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    )
}